wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.0
    start_time: 1637475405
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      4: 3.10.0
      5: 0.12.7
      8:
      - 1
      - 2
      - 3
      - 5
    visualize:
      pr:
        panel_config:
          fieldSettings:
            class: class
            x: recall
            y: precision
          panelDefId: wandb/area-under-curve/v0
          stringSettings:
            title: Precision v. Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: pr_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
    viz:
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
      roc:
        historyFieldSettings:
          key: roc
          x-axis: _step
        id: wandb/roc/v1
