wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.0
    start_time: 1637468904
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 2
      4: 3.10.0
      5: 0.12.7
      8:
      - 1
      - 2
      - 3
      - 5
